version: "3.3"
services:
  postgres-perf:
    container_name: postgres-perf
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - ./var/pgdata:/var/lib/postgresql/data
    networks:
      - network1
    ports:
      - "5434:5432"
networks:
  network1:
    name: pg-perf
    external: true
