version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - network1
    ports:
      - "8780:8780"
volumes:
  data:
networks:
  network1:
    name: pg-perf
    external: true